export const tmpCity = [
  { id: 'city_01', name: '서울', en_name: 'Seoul', region: '서울특별시' },
  { id: 'city_02', name: '수원', en_name: 'Suwon', region: '경기도' },
  { id: 'city_03', name: '부산', en_name: 'Busan', region: '부산광역시' },
  { id: 'city_04', name: '인천', en_name: 'Incheon', region: '인천광역시' },
  { id: 'city_05', name: '대전', en_name: 'Daejeon', region: '대전광역시' },
  { id: 'city_06', name: '대구', en_name: 'Daegu', region: '대구광역시' },
  { id: 'city_07', name: '광주', en_name: 'Gwangju', region: '광주광역시' },
  { id: 'city_08', name: '울산', en_name: 'Ulsan', region: '울산광역시' },
  { id: 'city_09', name: '세종', en_name: 'Sejong', region: '세종특별자치시' },
  { id: 'city_10', name: '춘천', en_name: 'Chuncheon', region: '강원특별자치도' },
  { id: 'city_11', name: '강릉', en_name: 'Gangneung', region: '강원특별자치도' },
  { id: 'city_12', name: '청주', en_name: 'Cheongju', region: '충청북도' },
  { id: 'city_13', name: '전주', en_name: 'Jeonju', region: '전북특별자치도' },
  { id: 'city_14', name: '포항', en_name: 'Pohang', region: '경상북도' },
  { id: 'city_15', name: '창원', en_name: 'Changwon', region: '경상남도' },
  { id: 'city_16', name: '제주', en_name: 'Jeju', region: '제주특별자치도' },
  { id: 'city_18', name: '태백', en_name: 'Taebaek', region: '강원특별자치도' },
  { id: 'city_20', name: '안동', en_name: 'Andong', region: '경상북도' },
  { id: 'city_21', name: '성남', en_name: 'Seongnam', region: '경기도' },
  { id: 'city_22', name: '고양', en_name: 'Goyang', region: '경기도' },
  { id: 'city_23', name: '용인', en_name: 'Yongin', region: '경기도' },
  { id: 'city_24', name: '안산', en_name: 'Ansan', region: '경기도' },
  { id: 'city_25', name: '파주', en_name: 'Paju', region: '경기도' },
  { id: 'city_26', name: '원주', en_name: 'Wonju', region: '강원특별자치도' },
  { id: 'city_27', name: '속초', en_name: 'Sokcho', region: '강원특별자치도' },
  { id: 'city_28', name: '충주', en_name: 'Chungju', region: '충청북도' },
  { id: 'city_29', name: '천안', en_name: 'Cheonan', region: '충청남도' },
  { id: 'city_30', name: '아산', en_name: 'Asan', region: '충청남도' },
  { id: 'city_31', name: '군산', en_name: 'Gunsan', region: '전북특별자치도' },
  { id: 'city_32', name: '여수', en_name: 'Yeosu', region: '전라남도' },
  { id: 'city_33', name: '목포', en_name: 'Mokpo', region: '전라남도' },
  { id: 'city_34', name: '순천', en_name: 'Suncheon', region: '전라남도' },
  { id: 'city_35', name: '나주', en_name: 'Naju', region: '전라남도' },
  { id: 'city_36', name: '경주', en_name: 'Gyeongju', region: '경상북도' },
  { id: 'city_37', name: '구미', en_name: 'Gumi', region: '경상북도' },
  { id: 'city_38', name: '진주', en_name: 'Jinju', region: '경상남도' },
  { id: 'city_39', name: '김해', en_name: 'Gimhae', region: '경상남도' },
]

export const regionList = [
  '서울특별시',
  '부산광역시',
  '대구광역시',
  '인천광역시',
  '광주광역시',
  '대전광역시',
  '울산광역시',
  '세종특별자치시',
  '경기도',
  '강원특별자치도',
  '충청북도',
  '충청남도',
  '전북특별자치도',
  '전라남도',
  '경상북도',
  '경상남도',
  '제주특별자치도',
]
